version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://statuspage:statuspage@test-db:5432/statuspage_test
      - REDIS_URL=redis://test-redis:6379/0
      - DJANGO_SETTINGS_MODULE=statuspage.statuspage.settings
    depends_on:
      - test-db
      - test-redis
    command: python -m pytest statuspage/tests -v --cov=statuspage

  test-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=statuspage_test
      - POSTGRES_USER=statuspage
      - POSTGRES_PASSWORD=statuspage
    tmpfs:
      - /var/lib/postgresql/data

  test-redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    tmpfs:
      - /data
