version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    volumes:
      - ./statuspage:/app/statuspage
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://statuspage:statuspage@db:5432/statuspage
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./statuspage:/app/statuspage
    environment:
      - DATABASE_URL=postgres://statuspage:statuspage@db:5432/statuspage
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "[r]qworker"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=statuspage
      - POSTGRES_USER=statuspage
      - POSTGRES_PASSWORD=statuspage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statuspage"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
