apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: statuspage
data:
  grafana.ini: |
    [server]
    domain = k8s-statuspa-grafanai-2c41c7352d-963734131.us-east-1.elb.amazonaws.com
    root_url = %(protocol)s://%(domain)s/grafana
    serve_from_sub_path = true
