apiVersion: v1
kind: ConfigMap
metadata:
  name: statuspage-config
  namespace: statuspage
data:
  DJANGO_SETTINGS_MODULE: "statuspage.settings"
  DJANGO_DEBUG: "0"
  ALLOWED_HOSTS: "*"  # We'll restrict this at the ALB/WAF level
  REDIS_URL: "redis://status-page-prod-redis.internal:6379/0"
  CELERY_BROKER_URL: "redis://status-page-prod-redis.internal:6379/1"
  # Monitoring configuration
  ENABLE_METRICS: "1"
  METRICS_RETENTION_DAYS: "14"  # Keep metrics for 14 days as per requirements
  MONITOR_CPU: "1"
  MONITOR_MEMORY: "1"
  MONITOR_LOAD: "1"
  MONITOR_DATABASE_RESPONSE: "1"
  MONITOR_DATABASE_USAGE: "1"
  MONITOR_UPTIME: "1"
  MONITOR_NETWORK: "1"
