apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: statuspage
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Status Page - Elad & Avior</title>
        <style>
            body {
                font-family: 'Helvetica Neue', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f7fa;
            }
            header {
                text-align: center;
                margin-bottom: 30px;
                padding-bottom: 20px;
                border-bottom: 1px solid #eaeaea;
            }
            h1 {
                color: #2c3e50;
                font-size: 32px;
                margin-bottom: 10px;
            }
            .subtitle {
                color: #7f8c8d;
                font-size: 18px;
                margin-top: 0;
            }
            .status-container {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
                gap: 20px;
                margin-bottom: 40px;
            }
            .status-card {
                background-color: #fff;
                border-radius: 8px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
                padding: 20px;
                transition: transform 0.2s ease;
            }
            .status-card:hover {
                transform: translateY(-5px);
                box-shadow: 0 7px 15px rgba(0, 0, 0, 0.1);
            }
            .status-card h2 {
                margin-top: 0;
                color: #34495e;
                font-size: 20px;
                display: flex;
                align-items: center;
            }
            .status-indicator {
                display: inline-block;
                width: 14px;
                height: 14px;
                border-radius: 50%;
                margin-right: 10px;
            }
            .status-operational {
                background-color: #2ecc71;
            }
            .status-maintenance {
                background-color: #f39c12;
            }
            .status-degraded {
                background-color: #e67e22;
            }
            .status-outage {
                background-color: #e74c3c;
            }
            .uptime {
                margin-top: 10px;
                font-size: 14px;
                color: #7f8c8d;
            }
            .metrics {
                margin-top: 15px;
                border-top: 1px solid #eee;
                padding-top: 15px;
            }
            .metrics div {
                margin-bottom: 5px;
                display: flex;
                justify-content: space-between;
            }
            .metrics span.label {
                color: #7f8c8d;
            }
            .metrics span.value {
                font-weight: 600;
                color: #34495e;
            }
            footer {
                text-align: center;
                margin-top: 50px;
                padding-top: 20px;
                border-top: 1px solid #eaeaea;
                color: #7f8c8d;
                font-size: 14px;
            }
            .refresh-time {
                text-align: right;
                color: #95a5a6;
                font-size: 14px;
                margin: 20px 0;
            }
            @media (max-width: 600px) {
                .status-container {
                    grid-template-columns: 1fr;
                }
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Elad & Avior - Status Page</h1>
            <p class="subtitle">Real-time status monitoring for all our systems</p>
        </header>
        
        <div class="refresh-time">Last updated: March 31, 2025 - 01:06:45 IDT</div>
        
        <div class="status-container">
            <div class="status-card">
                <h2><span class="status-indicator status-operational"></span> Web Application</h2>
                <p>Our customer-facing web application is fully operational.</p>
                <div class="uptime">Uptime: 99.99% (last 30 days)</div>
                <div class="metrics">
                    <div>
                        <span class="label">Response time:</span>
                        <span class="value">87ms</span>
                    </div>
                    <div>
                        <span class="label">Load:</span>
                        <span class="value">32%</span>
                    </div>
                </div>
            </div>
            
            <div class="status-card">
                <h2><span class="status-indicator status-operational"></span> API Services</h2>
                <p>All API endpoints are responding normally.</p>
                <div class="uptime">Uptime: 99.98% (last 30 days)</div>
                <div class="metrics">
                    <div>
                        <span class="label">Response time:</span>
                        <span class="value">112ms</span>
                    </div>
                    <div>
                        <span class="label">Requests/min:</span>
                        <span class="value">3,420</span>
                    </div>
                </div>
            </div>
            
            <div class="status-card">
                <h2><span class="status-indicator status-operational"></span> Database</h2>
                <p>Database systems operating at optimal levels.</p>
                <div class="uptime">Uptime: 100% (last 30 days)</div>
                <div class="metrics">
                    <div>
                        <span class="label">Query time:</span>
                        <span class="value">24ms</span>
                    </div>
                    <div>
                        <span class="label">Storage usage:</span>
                        <span class="value">48%</span>
                    </div>
                </div>
            </div>
            
            <div class="status-card">
                <h2><span class="status-indicator status-operational"></span> Servers</h2>
                <p>All server infrastructure is healthy.</p>
                <div class="uptime">Uptime: 99.95% (last 30 days)</div>
                <div class="metrics">
                    <div>
                        <span class="label">CPU usage:</span>
                        <span class="value">37%</span>
                    </div>
                    <div>
                        <span class="label">Memory usage:</span>
                        <span class="value">42%</span>
                    </div>
                </div>
            </div>
            
            <div class="status-card">
                <h2><span class="status-indicator status-operational"></span> CDN/Edge Network</h2>
                <p>Content delivery network operating at full capacity.</p>
                <div class="uptime">Uptime: 99.99% (last 30 days)</div>
                <div class="metrics">
                    <div>
                        <span class="label">Latency:</span>
                        <span class="value">31ms</span>
                    </div>
                    <div>
                        <span class="label">Cache hit ratio:</span>
                        <span class="value">94%</span>
                    </div>
                </div>
            </div>
            
            <div class="status-card">
                <h2><span class="status-indicator status-operational"></span> External Integrations</h2>
                <p>All third-party services and integrations functioning correctly.</p>
                <div class="uptime">Uptime: 99.87% (last 30 days)</div>
                <div class="metrics">
                    <div>
                        <span class="label">Response time:</span>
                        <span class="value">156ms</span>
                    </div>
                    <div>
                        <span class="label">Error rate:</span>
                        <span class="value">0.02%</span>
                    </div>
                </div>
            </div>
        </div>
        
        <footer>
            <p>© 2025 Elad & Avior Status Page - Powered by AWS EKS</p>
            <p>This page automatically updates every 60 seconds.</p>
        </footer>
        
        <script>
            // Simple script to update the "Last updated" time every 60 seconds
            function updateTime() {
                const now = new Date();
                const options = { 
                    year: 'numeric', 
                    month: 'long', 
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                    second: '2-digit',
                    timeZoneName: 'short'
                };
                document.querySelector('.refresh-time').textContent = 'Last updated: ' + now.toLocaleDateString('en-US', options);
            }
            
            setInterval(updateTime, 60000);
        </script>
    </body>
    </html>
