apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: statuspage
data:
  queries.yaml: |
    pg_database:
      query: "SELECT d.datname as database, pg_database_size(d.datname) as size_bytes FROM pg_database d where datname not in ('template0', 'template1', 'postgres')"
      metrics:
        - database:
            usage: "LABEL"
            description: "Database name"
        - size_bytes:
            usage: "GAUGE"
            description: "Database size in bytes (High Priority)"
    
    pg_stat_activity:
      query: "SELECT count(*) as connections, datname as database FROM pg_stat_activity GROUP BY datname"
      metrics:
        - connections:
            usage: "GAUGE"
            description: "Number of active connections (Medium Priority)"
        - database:
            usage: "LABEL"
            description: "Database name"
    
    pg_stat_database:
      query: |
        SELECT
          d.datname as database,
          COALESCE(sum(t.calls), 0) as statements,
          COALESCE(sum(t.total_exec_time), 0) as total_exec_time_ms
        FROM pg_database d
        LEFT JOIN pg_stat_statements t ON t.dbid = d.oid
        GROUP BY d.datname
      metrics:
        - database:
            usage: "LABEL"
            description: "Database name"
        - statements:
            usage: "COUNTER"
            description: "Total number of SQL statements executed (Medium Priority)"
        - total_exec_time_ms:
            usage: "COUNTER"
            description: "Total execution time in milliseconds (High Priority)"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: statuspage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.10.1
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: statuspage-secrets
              key: database-url
        ports:
        - containerPort: 9187
          name: metrics
        args:
        - "--extend.query-path=/etc/postgres-exporter/queries.yaml"
        volumeMounts:
        - name: queries-config
          mountPath: /etc/postgres-exporter
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: queries-config
        configMap:
          name: postgres-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: statuspage
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  selector:
    app: postgres-exporter
  ports:
  - port: 9187
    targetPort: metrics
    protocol: TCP
    name: metrics
