apiVersion: v1
kind: Secret
metadata:
  name: statuspage-secrets
  namespace: statuspage
type: Opaque
stringData:
  DATABASE_URL: "postgresql://statuspage:${DB_PASSWORD}@${DB_HOST}:5432/statuspage"
  DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_REGION: "us-east-1"
