apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: statuspage
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: $(kubectl create secret docker-registry regcred --docker-server=992382545251.dkr.ecr.us-east-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password --region us-east-1) --dry-run=client -o jsonpath="{.data.\.dockerconfigjson}")
