apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-web
  namespace: statuspage
  labels:
    app: statuspage
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
      component: web
  template:
    metadata:
      labels:
        app: statuspage
        component: web
    spec:
      containers:
      - name: web
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
        command: ["gunicorn", "--chdir", "statuspage", "--bind", "0.0.0.0:8000", "statuspage.wsgi:application"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: DB_NAME
          value: "statuspage"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statuspage-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          value: "statuspage-db.statuspage.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: CELERY_BROKER_URL
          value: "redis://statuspage-redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://statuspage-redis:6379/0"
        envFrom:
        - configMapRef:
            name: statuspage-config
      imagePullSecrets:
      - name: regcred
