apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-worker
  namespace: statuspage
  labels:
    app: statuspage
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
      component: worker
  template:
    metadata:
      labels:
        app: statuspage
        component: worker
    spec:
      containers:
      - name: worker
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
        command: ["python", "statuspage/manage.py", "rqworker", "default"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statuspage-secrets
              key: DB_PASSWORD
        - name: CELERY_BROKER_URL
          value: "redis://statuspage-redis:6379/0"
        - name: CELERY_RESULT_BACKEND
          value: "redis://statuspage-redis:6379/0"
        envFrom:
        - configMapRef:
            name: statuspage-config
      imagePullSecrets:
      - name: regcred
