apiVersion: v1
kind: Pod
metadata:
  name: django-debug
  namespace: statuspage
spec:
  containers:
  - name: debug
    image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
    command: ["/bin/bash", "-c", "cd statuspage && python manage.py shell -c 'import os; from pathlib import Path; from django.conf import settings; print(f\"STATIC_URL: {settings.STATIC_URL}\"); print(f\"PROJECT ROOT: {os.getcwd()}\"); print(f\"STATIC FILES DIRS: {getattr(settings, \"STATICFILES_DIRS\", [])}\"); print(f\"STATIC ROOT: {getattr(settings, \"STATIC_ROOT\", \"Not Set\")}\"); print(f\"Installed Apps: {settings.INSTALLED_APPS}\");'; sleep 3600"]
    env:
    - name: DB_NAME
      value: "statuspage"
    - name: DB_USER
      value: "statuspage"
    - name: DB_PASSWORD
      value: "postgres"
    - name: DB_HOST
      value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
    - name: DB_PORT
      value: "5432"
    - name: DJANGO_SETTINGS_MODULE
      value: "statuspage.settings"
