apiVersion: v1
kind: Pod
metadata:
  name: django-debug-fixed
  namespace: statuspage
spec:
  containers:
  - name: debug
    image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
    command: ["/bin/bash", "-c", "cd statuspage && python -c 'import os; from pathlib import Path; from django.conf import settings; print(\"STATIC_URL:\", getattr(settings, \"STATIC_URL\", \"Not Set\")); print(\"PROJECT ROOT:\", os.getcwd()); print(\"STATICFILES_DIRS:\", getattr(settings, \"STATICFILES_DIRS\", [])); print(\"STATIC_ROOT:\", getattr(settings, \"STATIC_ROOT\", \"Not Set\")); print(\"Installed Apps:\", settings.INSTALLED_APPS); print(\"DEBUG:\", getattr(settings, \"DEBUG\", False));'; sleep 3600"]
    env:
    - name: DB_NAME
      value: "statuspage"
    - name: DB_USER
      value: "statuspage"
    - name: DB_PASSWORD
      value: "postgres"
    - name: DB_HOST
      value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
    - name: DB_PORT
      value: "5432"
    - name: DJANGO_SETTINGS_MODULE
      value: "statuspage.settings"
