apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-web-with-static
  namespace: statuspage
  labels:
    app: statuspage
    component: web-static
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
      component: web-static
  template:
    metadata:
      labels:
        app: statuspage
        component: web-static
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      volumes:
      - name: static-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
      initContainers:
      - name: collectstatic
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
        command: ["python", "statuspage/manage.py", "collectstatic", "--noinput"]
        env:
        - name: DB_NAME
          value: "statuspage"
        - name: DB_USER
          value: "statuspage"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_HOST
          value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "statuspage-redis"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_SETTINGS_MODULE
          value: "statuspage.settings"
        volumeMounts:
        - name: static-volume
          mountPath: /app/statuspage/static
      containers:
      - name: web
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
        command: ["gunicorn", "--chdir", "statuspage", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "120", "statuspage.wsgi:application"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: DB_NAME
          value: "statuspage"
        - name: DB_USER
          value: "statuspage"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_HOST
          value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "statuspage-redis"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_SETTINGS_MODULE
          value: "statuspage.settings"
        volumeMounts:
        - name: static-volume
          mountPath: /app/statuspage/static
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-volume
          mountPath: /app/statuspage/static
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
      imagePullSecrets:
      - name: regcred
