apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-web
  namespace: statuspage
  labels:
    app: statuspage
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
      component: web
  template:
    metadata:
      labels:
        app: statuspage
        component: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
        command: ["gunicorn", "--chdir", "statuspage", "--bind", "0.0.0.0:8000", "--workers", "4", "--timeout", "120", "statuspage.wsgi:application"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        - name: DB_NAME
          value: "statuspage"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: statuspage-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com" 
        - name: DB_PORT
          value: "5432"
        - name: DB_CONNECT_TIMEOUT
          value: "60"
        - name: DB_CONNECT_RETRIES
          value: "5"
        - name: REDIS_HOST
          value: "statuspage-redis"
        - name: STATUS_PAGE_CONFIGURATION
          value: "statuspage.configuration"
        - name: PYTHONUNBUFFERED
          value: "1" 
        - name: DJANGO_SETTINGS_MODULE
          value: "statuspage.settings"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: statuspage-web
  namespace: statuspage
  labels:
    app: statuspage
    component: web
spec:
  selector:
    app: statuspage
    component: web
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
