apiVersion: v1
kind: ConfigMap
metadata:
  name: static-fix-script
  namespace: statuspage
data:
  fix-static.sh: |
    #!/bin/bash
    cd /app
    pip install whitenoise
    echo "Adding whitenoise to settings..."
    grep -q "WhiteNoiseMiddleware" /app/statuspage/statuspage/settings.py || sed -i "s/MIDDLEWARE = \[/MIDDLEWARE = \[\n    'whitenoise.middleware.WhiteNoiseMiddleware',/" /app/statuspage/statuspage/settings.py
    echo "Setting DEBUG to True..."
    grep -q "DEBUG = True" /app/statuspage/statuspage/settings.py || sed -i "s/DEBUG = .*/DEBUG = True/" /app/statuspage/statuspage/settings.py
    echo "Running collectstatic..."
    cd /app/statuspage
    python manage.py collectstatic --noinput
    echo "Static files fix complete."
