apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-web-styled
  namespace: statuspage
  labels:
    app: statuspage
    component: web-styled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
      component: web-styled
  template:
    metadata:
      labels:
        app: statuspage
        component: web-styled
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:styled
        command: ["gunicorn", "--chdir", "statuspage", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "120", "statuspage.wsgi:application"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
        env:
        - name: DB_NAME
          value: "statuspage"
        - name: DB_USER
          value: "statuspage"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_HOST
          value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "statuspage-redis"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_SETTINGS_MODULE
          value: "statuspage.settings"
      imagePullSecrets:
      - name: regcred
