apiVersion: v1
kind: Secret
metadata:
  name: statuspage-secrets
  namespace: statuspage
type: Opaque
stringData:
  DB_PASSWORD: postgres
  DB_USER: statuspage
  SECRET_KEY: ij2o3ijr2o3ijro2j3ro2j3roi23roij
