apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-worker
  namespace: statuspage
  labels:
    app: statuspage
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
      component: worker
  template:
    metadata:
      labels:
        app: statuspage
        component: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9191"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: worker
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/statuspage-app:latest
        command: ["python", "statuspage/manage.py", "rqscheduler"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        env:
        - name: DB_NAME
          value: "statuspage"
        - name: DB_USER
          value: "statuspage"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_HOST
          value: "status-page-prod-db.cx248m4we6k7.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "statuspage-redis"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_SETTINGS_MODULE
          value: "statuspage.settings"
      imagePullSecrets:
      - name: regcred
